### ISSUE TITLE
Instructions how to install to own server?

### ISSUE THREAD

**Issue by anywhere3d** [bulkpinner/bulkpinner#1]
Can you include some instructions how to install to own server please? I am totaly lost with glup files. Thank you.

**Comment by denno020** [comment]
Hi mate,

If you open up 1 command terminals, and run `npm start` and `npm run dev`, that will start a local server to serve the files (`npm start`), and also build and then watch the source file directory (`npm run dev`)

**Comment by anywhere3d** [comment]
Super! Thanks!

**Comment by nhokzer0** [comment]
I can't use it on my server, can you support me in this case.
When i upload source code, it can't load template and any function.
