### ISSUE TITLE
Upload from Excel

### ISSUE THREAD

**Issue by silviarehn** [bulkpinner/bulkpinner#10]
Hello, i love you job and use it a lot! I would like to give you a suggestion. Upload from excel =) and another idea is bulk upload all images from a post. So, you will have a super bulk uploader. First set to upload a list of posts, and than, all imagens on that post. Job its done! You could easily charge for it! Tanks a lot!

**Comment by bulkpinner** [comment]
Hi Silviarehn,

Thanks for your kinds words! They're interesting suggestions. I'm not sure I'll ever be able to support uploading from Excel. What I feel is the beauty of Bulk Pinner is that it's so simple, so adding features will be done sparingly, so as to not make it too complicated.

Your second suggestion of pinning all images from a post, that is something I have been thinking about. Creating a browser extension that will work with Bulk Pinner could be pretty cool I think, but that's on the road map for a future add on.

In the mean time, there are browser extensions that already exist which will download all of the images from a webpage, which you can then upload to Bulk Pinner and save. I personally use "Image Downloader" by Vlad Sabev in Chrome.

Thanks again for your suggestions,
Luke

**Comment by silviarehn** [comment]
Thank you for the return. Your work is amazing. You could be making some
money from it!

*Silvia Rehn* *|*  Diretora de Marketing, Novos Negócios e Conteúdo

*Magazine Feminina <https://www.magazinefeminina.com/>*

+55 21 980126044 – Skype: silvia.rehn  |
silvia.rehn@magazinefeminina.com.br <silvia.rehn@magazinegeminina.com.br>

Esta mensagem pode conter informação confidencial, particular, privilegiada
ou legalmente protegida contra sua revelação e uso por terceiros. Se a
tiver recebido indevidamente, solicitamos removê-la de seu sistema e
comunicar ao remetente. Obrigada

2018-08-10 19:52 GMT-03:00 Luke Denton <notifications@github.com>:

**Comment by silviarehn** [comment]
Hi Luke, Good Morning

I'm desperate. Bulkpinner is down! After all this time, I never thought
Pinterest would do that. I am very sad.
The bulkpinner is excellent. If you have something news, to tell me, any
tips, I'm researching some other way to get the job done without having to
pin one by one.
That is very unfair... With you, and with me too =(


*Silvia Rehn* *|*  Diretora de Marketing, Novos Negócios e Conteúdo

*Magazine Feminina <https://www.magazinefeminina.com/>*

+55 21 980126044 – Skype: silvia.rehn  |
silvia.rehn@magazinefeminina.com.br <silvia.rehn@magazinegeminina.com.br>

Esta mensagem pode conter informação confidencial, particular, privilegiada
ou legalmente protegida contra sua revelação e uso por terceiros. Se a
tiver recebido indevidamente, solicitamos removê-la de seu sistema e
comunicar ao remetente. Obrigada


Em sex, 10 de ago de 2018 às 19:52, Luke Denton <notifications@github.com>
escreveu:

**Comment by silviarehn** [comment]
Hello Luke, about Bulk Pinner, can not load folders anymore. Did you see
that?

Em sex, 10 de ago de 2018 às 19:52, Luke Denton <notifications@github.com>
escreveu:

**Comment by bulkpinner** [comment]
Hi Silviarehn,

I'm aware Bulk Pinner isn't working anymore. It's very frustrating, as Pinterest haven't been responding to any of my contact attemps.

At this stage, I'm not sure in what capacity Bulk Pinner might be able to come back

**Comment by silviarehn** [comment]
No problem, I will be forever grateful to you. Your system helped me a lot
to start some business. Thank you. Now, I will try to create an API via
Laravel to raise random pins. Do you think it might work or is Pinterest
really closing all the doors to all the APIs in the world?

Em ter, 29 de out de 2019 às 09:58, Luke Denton <notifications@github.com>
escreveu:

**Comment by bulkpinner** [comment]
I don't know, all I know is that they're blocking my application, likely because I'm not giving them money. I'm super bitter about Pinterest these days, upon closer inspection it seems they couldn't care less about their users, it's all about the ads they can plaster in front of people's faces

**Comment by silviarehn** [comment]
Luke, do not loose energy with this. You are a creator and you will create
again, very nice things. Dont you see? Its not about pinterest. Its
aboutyou made something that people from all over the globe used. And now
this people are missing it. You made something great, you can do again.
Focus on it

Em ter, 29 de out de 2019 17:15, Luke Denton <notifications@github.com>
escreveu:
