### ISSUE TITLE
Default to filename

### ISSUE THREAD

**Issue by fredguth** [bulkpinner/bulkpinner#11]
Pinterest note is required, but there should be an option to BATCH  use filename as default.

**Comment by bulkpinner** [comment]
Hi Fred, do you pay to use the Bulk Pinner application?

**Comment by fredguth** [comment]
No.

**Comment by bulkpinner** [comment]
That's right, so some manners or a little bit of gratitude would go a long way.

Bulk Pinner has the ability to set the note to the filename of the uploaded file, however it has to be done on each individual pin preview.

You're more than welcome to submit a pull request for review that adds the batch feature

**Comment by fredguth** [comment]
I am sorry if you understood that as a demand.
