### ISSUE TITLE
Hello Mr

### ISSUE THREAD

**Issue by elwinjose** [bulkpinner/bulkpinner#12]
Hello Mr. Can explain how to fill the description and URL in case it is a massive rise.?
Please thank you very much for your attention

**Comment by bulkpinner** [comment]
Hi elwinjose,

I'm going to assume that you want to automatically fill in all the description and URL's for each pin preview, without having to manually copy and paste to each of them?

There is a keyboard shortcut, if you press > 3 times (so hold shift, and press the full stop key), the description and URL from the first pin preview will be copied to all other pin previews.

If you're on mobile, the feature exists in the side menu.

Thank you for using Bulk Pinner
