### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Blinndox** [bulkpinner/bulkpinner#13]
Hey there!

Any chance you'd add an option to select multiple pins to pin to the same board?  I have nearly 500 boards and pin hundreds a night. When I mass upload it can be a pain to go through and type the name of every board into the drop down boxes to get the right board.  Thank you! Keep up the amazing work!

**Comment by bulkpinner** [comment]
Hi Blinndox,

Thanks for your kind words.

As for your feature request, I believe I already have what you need.. In the middle of the actions toolbar, there is a label "Send all images to board". If you choose one of your board names here, then all of the images that you have currently loaded in to Bulk Pinner will be sent to that board (you'll see their individual board selectors update). So you can change this "Send all images to board" select, and then if there are some images that you've already loaded into Bulk Pinner that you would like to send to another board, you can change the board on those individual images.

Please let me know if I have misunderstood your requests.

Kind regards,
Luke

**Comment by Blinndox** [comment]
Hey Luke!!

So I know about the bar but when I’m uploading pins I usually have a couple hundred and they are cosplayers wearing various costumes and characters. There are times when I have a dozen or more pins they’re going to. The bar is great if I want to just upload one or two characters at a time but that would be very tedious. I was referring to a way I could select multiple pins at a time and just select the board once and then repeat over and over for each grouping of pins. Does that make sense?

Justin

**Comment by bulkpinner** [comment]
Hi Justin,

So you want to target only a few pins to send them all to a certain board? That's an interesting idea. I can add it to the wishlist of features for Bulk Pinner, so it might appear in the near future :).

Thanks for your suggestion!
