### ISSUE TITLE
Feedback - tool errors

### ISSUE THREAD

**Issue by RealDavidoff** [bulkpinner/bulkpinner#14]
Hello,
I just tried your tool, my own way, because your youtube video is not enlightening, try watching it with the eyes of someone NOT having programmed your tool... it's just showing some ueber fast mouseclicks and screen changes that no one can reproduce.

Either way, wanted to give you tool specific feedback too: 
- so i selected 5 images from local drive (did I do as you intend it?)
- the tool nicely creates 5 pins, prompting in each to add description and URL, great
- but regardless whether you choose a board from the outset, or now, the tool does not "see" the board if it's a child board. It seems to only "see" main boards.

Well, on pinterest you need to organize well, so all our boards are subdivided further into child boards (only one level down).

Pinterest did allow me to re-associate all pins to the correct board, but by the time I was finished I could have pinned all images correctly without using the tool

So, I believe the tool is a great start. And if it could actually pin to the correct board it probably would save a lot of time, yes. Do you agree?

**Comment by bulkpinner** [comment]
Hi RealDavidoff,

I'm sorry my free tool doesn't meet your expectations.

Kind regards,
Luke
