### ISSUE TITLE
Authorization Fails

### ISSUE THREAD

**Issue by abhinavrohatgi** [bulkpinner/bulkpinner#15]
Hi, 

Thanks for creating such a wonderful application. I was using the application perfectly but after some time it is not loading any pins.  I have uploaded only 10 pins with your application only. Below is the error which i am getting every time i am trying to log in. 

{"status": "failure", "message": "The authorization grant is invalid", "code": 283, "data": "Invalid Application ID"}

**Comment by abhinavrohatgi** [comment]
The application is working perfectly after your guidance. 

Once small suggestion instead of clicking photos or the icon on the right side to use the photo name if you can put a radio button which allows users to select all and use the photo name it would be really nice. 

Thanks for the help and your application indeed saved a lot of time in uploading photos. 

Cheers !

**Comment by bulkpinner** [comment]
Thanks for the suggestion!

I'll add it to the feature request list and hopefully be able to release a bunch of features in the near future.

Thanks
