### ISSUE TITLE
Connection to Pinterest account?

### ISSUE THREAD

**Issue by jefflamonica** [bulkpinner/bulkpinner#16]
Hi, Luke -
Just discovered your app, and trying to connect to my Pinterest account. Do boards need to be public to connect? I'm experimenting on a new, private board. Also, Pinterest keeps throwing an error like this:

![image](https://user-images.githubusercontent.com/44300200/47232172-939d9a00-d394-11e8-9ff3-257649193ddf.png)

Any guidance you can provide will help immensely. --Jeff

**Comment by jefflamonica** [comment]
making the board public allowed Bulk Pinner to access the board. Error went away.

**Comment by bulkpinner** [comment]
Hi Jeff,

Unfortunately Pinterest doesn't expose private boards over their API, so the only way to add to or otherwise edit them is on Pinterest's website.

Hope you find Bulk Pinner useful.

Kind regards,
Luke
