### ISSUE TITLE
Will not upload

### ISSUE THREAD

**Issue by Agarea** [bulkpinner/bulkpinner#17]
App is connected, authorized, etc on Pinterest and it will not upload a bulk batch or a single pin.

**Comment by bulkpinner** [comment]
Hi Agarea, thanks for letting me know.

Could you please provide some more information;
- what happens when you try and add images to Bulk Pinner?
- what happens when you click on the Pin button?

**Comment by surendarkumar** [comment]
It has happened with me as well. It is showing that Pin are uploading for infinite time. After hours, no pins get uploaded

**Comment by bulkpinner** [comment]
Hi surendarkumar, thanks for adding your feedback.

There is currently a UI bug such that if the pin isn't created on Pinterest for whatever reason, the loading indicator doesn't disappear. So I would assume Pinterest has blocked the pin from being created (either the session token had become invalid, or Pinterest blocked the URL, or some other reason). Either way, this is certainly something I will need to fix.

Thanks again

**Comment by Agarea** [comment]
Hi Luke,

I hit bulk upload or whatever that button says and then the circles just
keep spinning and nothing is uploaded onto pinterest.

**Comment by bulkpinner** [comment]
Could you please try "Disconnecting" Bulk Pinner from Pinterest, and then re-authorizing? (There is a disconnect button in the menu at the top right of the desktop page, and in the slide out menu on mobile). Once you've disconnected, please also make sure you're viewing the HTTPS version of the website. I've been seeing some difficulties with people not being properly redirected. The URL that should be used is [https://bulkpinner.app](https://bulkpinner.app)

Thanks

**Comment by Agarea** [comment]
It's still not working...

**Comment by bulkpinner** [comment]
Hi Agarea,

Could you please open your browers developer tools and switch to the network tab, then try clicking the Pin button in Bulk Pinner?

There will be new requests made, which I assume will turn red, which means they failed. Clicking on one of the failed requests should show the response from Pinterest as to why it was declined. If you could post that message back here, we can debug further.

Thanks,
Luke

**Comment by Agarea** [comment]
[image: Screen Shot 2018-11-02 at 3.11.06 PM.png]
Hi Luke,

This is what it did when I tried that.

**Comment by denno020** [comment]
Thanks for the image Agarea, but it doesn't appear to have attached correctly.. Could you please have another go? Alternatively you could upload it to Google Drive or Dropbox, and share the link with me.

Thanks,
Luke

**Comment by ahuyblog** [comment]
I also have the same situation when uploading multiple photos at the same time!
And here is the log from the network tab: https://app.box.com/s/vk3xkui3662b5yd6mfx64zszw2v05vqg

The problem occurs when there are too many requests, in my case is from request 429!

**Comment by denno020** [comment]
Thanks for the update ahuyblog.

Does that mean you were trying to pin ~430 images at once? Wow, that's impressive! To be completely honest, I haven't "stress tested" Bulk Pinner, so I don't know how many pins can be uploaded simultaneously, before I need to work out a way to stagger the requests.

Out of interest, how many images were you trying to pin when you encountered this error?

**Comment by ahuyblog** [comment]
Hi denno020!

Not long ago, I can upload about 700 photos at the same time. But it seems that pinterest now limits the number of requests. 

The problem is that when you have pinterest limit the number of requests, you will not be able to upload photos anymore. You have to wait a while for the upload to continue through bulkpinner.app

So if you do not upload anymore, you should clear the finished image, then click the pin button again. If you still can not, then you should wait for the time (I do not know how long) and then upload again.

**Comment by denno020** [comment]
Ah right! Pinterest does impose a limit of 1000 pins per hour per user, so if you're pinning 700 images at once, then it's quite likely you'll hit that limit. I do have plans on reporting the number of pins that a user has left for the hour, however I didn't think people would be pinning as much as that, and therefore whether it would be all that useful!
Perhaps I should revisit that feature :)

**Comment by lordton** [comment]
Thx A LOT for the app guys!
Also tried uploading several hundreds of photos and hit the limit. Had a massive collection of pictures in folders on my computer for ages!

Pinterest API is pain, but looks like it's getting a bit better.

Some thoughts on UI:

1) You can add a disclaimer about 1000 post per hour/user, so people don't get confused
2) Maybe it's nice to show the available boards before selecting a picture to upload (it;s the only way to know if you reached the limit so far)
3) Perhaps that's too specific, but if the photo is uploaded from local computer, it has no info about the source of image. I dont' know if it's technically possible, but google image search link to the picture would be really nice.
4) Also using the file name as photo reference is really useful, but batch function could be added to it too.
