### ISSUE TITLE
Images Quality

### ISSUE THREAD

**Issue by ariburaco** [bulkpinner/bulkpinner#18]
It is a really great script. I loved it. But, the images qualities that I've pinned with bulkpinner are really low when I upload my higher res. images. Do u have use any compression for uploading images?
Thanks

**Comment by bulkpinner** [comment]
Hi ariburaco, thanks for your kind words!

That's very interesting about the image quality. I don't specifically compress the images, but I do pass them to Pinterest through the API as base64 encoded data, so perhaps that is losing a bit of the quality.

Is it possible to see a before and after example of one of the images? Would be interested in the size of the original image, and then how that appears on Pinterest after being pinned through my tool.

Thanks!
Luke

**Comment by ariburaco** [comment]
Hey Luke,
Thanks for the info. I've realized that when I've added the link for a pin, it reduces the quality for preview. But If I don't add the link, Pinterest shows the actual image with original sizes. So, it is about the Pinterest. Bulkpinner works perfectly :)

Btw, another question for you. Since the whole project open-source, how can I use the script in my localhost. I've not used any API and Javascript but I really want to start with Bulkpinner. Is there any guide for that? I've tried to move files on Xampp localhost and Css codes are not proper and authorization wasn't succesful. 

Thanks for sharing this script with us :)
Burak

**Comment by bulkpinner** [comment]
Thanks for that insight Burak! Very interesting that adding a link would reduce the quality of the image.

I haven't written any specific instructions unfortunately, but you're more than welcome to checkout the repository and much around with it to get it working :).
