### ISSUE TITLE
API failure

### ISSUE THREAD

**Issue by dgcaste** [bulkpinner/bulkpinner#19]
When I go to authorize, I get:

{"status": "failure", "message": "You are not permitted to access that resource.", "code": 7, "data": "The provided redirect_uri http://bulkpinner.app/ does not match any of the registered redirect URIs."}

**Comment by dgcaste** [comment]
Tried https and it worked!

**Comment by bulkpinner** [comment]
Thanks for letting me know you figured it out! :)
