### ISSUE TITLE
I cannot choose a board. The list of boards doesn't appear

### ISSUE THREAD

**Issue by jpeters8602336923** [bulkpinner/bulkpinner#21]

**Comment by bulkpinner** [comment]
Hi jpeters,

Are you trying to view public or private boards?

Bulk Pinner isn't able to work with private boards because Pinterest doesn't make them available over the API, so using the app, pins can only be made to public boards that you own.

Thanks,
Luke

**Comment by jpeters8602336923** [comment]
I am using only my public boards.

**Comment by bulkpinner** [comment]
Hmm.. That's interesting.. Could you please try disconnecting and then re-authorizing Bulk Pinner. This will eliminate any issues with access keys possibly expiring or being lost.
If that doesn't help, could you please pop open the developer tools, and see if there are any errors on the Console, or any red highlighted requests in the network tab (to see network activity, you'll need to have devtools open before refreshing the page)

Thanks,
Luke

**Comment by jpeters8602336923** [comment]
Ok, I will try that and let you know.
J
