### ISSUE TITLE
Keyboard shorcuts

### ISSUE THREAD

**Issue by erossplayla** [bulkpinner/bulkpinner#3]
Hello!
Great app! Thanks for sharing this!
Several days ago, on an older computer i could see a wheel in up left corner which allowed auto fill description and link.
Now its missing and if i go to bottom to Keyboard Shortcuts and press 3 times >>> doesn't work.
I am doing something wrong ? Or might be something related with Chrome updates?

Thank you.

![keyboard shortcuts](https://user-images.githubusercontent.com/34010912/41764306-60391592-7609-11e8-96b0-22df10a076c2.JPG)

**Comment by denno020** [comment]
Thanks for the bug report!

The auto fill feature has only recently been put into a side menu - on mobile, so I'm not too sure what you might be referencing..

The keyboard shortcut should still be working though. Can you please confirm that the Bulk Pinner tab is active when you type '>' 3 times, and that there isn't a text field active (so you're not actually typing '>' into a description field 3 times).

If both the tab is active, and no text fields are active, but it's still not working, can you please provide which browser you're using, including the exact version number, and which operating system you're using.

Thanks,
Luke

**Comment by erossplayla** [comment]
Worked with "> shift > shift >"
First time i tough was the arrow >
Keyboard shortcuts work.
Google Chrome is up to date-Version 67.0.3396.87 (Official Build) (64-bit)  
Windows 10 Pro

Also i think its very important you to limit / display max no. uploads 1000 cause there could be some internet fellows who might abuse app.
Get a domain or i can buy 1y and donate it to you , give you the credentials etc.
This is an awesome tool.
Honestly i would copy it into one domain so ill be sure it won't disappear.
If there is anything i can help, give a push anytime.

**Comment by denno020** [comment]
The keyboard shortcut works by typing `SHIFT` + `.` 3 times, so holding SHIFT and then pressing the full stop button. Did you say that it worked now?

Thanks for the feedback. Pinterest already limits the number of uploads a single user can make during one hour, so there is no limiting needed by me, I just need to update the interface to let a user know when they have hit that limit

Thanks for the suggestion of the domain name. I've already got one, [bulkpinner.app](https://bulkpinner.app), however when I applied it to the GitHub Page, `https` didn't work properly, so I need to figure out what is happening there and try again. Currently going to [bulkpinner.app](https://bulkpinner.app) will redirect to the GitHub page.

I'm glad you like the tool :).

Please update this issue as closed if the feature did work through the keyboard shortcut.

Thanks

**Comment by erossplayla** [comment]
Everything ok.
And if you proceed with ads, would be perfect if redirect in new tab cause if you click and you need to select img and upload again its annoying.
Here is a tip, nothing affiliate: https://www.123-reg.co.uk/    .uk 99p. co.uk 99p.london £9.99.com £6.99
Have a nice day!
