### ISSUE TITLE
Page stalls when adding multiple photos

### ISSUE THREAD

**Issue by GFultz** [bulkpinner/bulkpinner#32]
it just sits there spinning and spinning after pressing the pin button this happened on 2 pins and 150 pins 

running chrome on windows 10

**Comment by GFultz** [comment]
after countless hours and trying different ways and on different computers, I'm just gonna assume this is broken nice idea tho if it actually worked.   cheers!

**Comment by bulkpinner** [comment]
Hi Greg,

That's a shame that you're having trouble with the app. I've been looking at the logs at it appears other people are using it just fine 🤔.

Are you familiar with a browsers Developer Tools at all? Would it be possible to inspect some network requests that are made once you click the Pin button? If they're coming up red, then they might be able to give a few hints as to the problem you're facing.

Thanks,
Luke

**Comment by GFultz** [comment]
Thanks, Luke  I don't know what the problem is I used it for a few images
when I first got on it to test it out and it went fine so i went for the
big upload and did 150 pins and it just sat and spun for multiple hours so
I tried a smaller amount went down to 50 and smaller again down to 15
nothing and then did just 1 pin nothing. so I don't know if it's on my end
or yours but it's not working and i've tried it on multiple different
computers.

I'll try again later maybe it is my network.



Greg Fultz  Lead GeeK (IT Specialist)
GEFNET Computer/Internet Sales and Service
p: (217) 960-GeeK (4335) m: (575) 415-GREG (4734)
w: www.GEFNET.com <http://www.gefnet.com/> e: support@gefnet.com
a: 1400 Charleston Ave, Suite 230 Mattoon, IL 61938

Follow us:

<http://facebook.com/gefnet> <https://www.linkedin.com/company/2398273/>
<http://www.twitter.com/gefnet> <http://www.instagram.com/gefnet>
<https://plus.google.com/104550302158164371067>
Need to Chat? Set up a meeting with me! GEFNET.com/BookTime
<http://gefnet.com/BookTime>

GEFNET's Blog - Latest Blog Post <https://gfnt.me/LatestBlogPost> | 3
Essential Tips for your New or Current Computer <https://gfnt.me/3ETM>

**Comment by bulkpinner** [comment]
I'm curious, are you attaching a URL to the pin you're creating? It's possible that Pinterest is declining the Pin from being created because of the URL, as they have identified it as spam for one reason or another.. That could be something worth checking

**Comment by bulkpinner** [comment]
It's likely that Pinterest allowed the first couple of pins because they were using a URL that Pinterest didn't know anything about. After the first one was created, it could have automatically been put onto a spam list, meaning any future pins with that URL wouldn't work.. 
Have you been able to pin with a different/no URL?

**Comment by GFultz** [comment]
I got on there and tried some more today and it was flawless so maybe just
my network.



Greg Fultz  Lead GeeK (IT Specialist)
GEFNET Computer/Internet Sales and Service
p: (217) 960-GeeK (4335) m: (575) 415-GREG (4734)
w: www.GEFNET.com <http://www.gefnet.com/> e: support@gefnet.com
a: 1400 Charleston Ave, Suite 230 Mattoon, IL 61938

Follow us:

<http://facebook.com/gefnet> <https://www.linkedin.com/company/2398273/>
<http://www.twitter.com/gefnet> <http://www.instagram.com/gefnet>
<https://plus.google.com/104550302158164371067>
Need to Chat? Set up a meeting with me! GEFNET.com/BookTime
<http://gefnet.com/BookTime>

GEFNET's Blog - Latest Blog Post <https://gfnt.me/LatestBlogPost> | 3
Essential Tips for your New or Current Computer <https://gfnt.me/3ETM>

**Comment by bulkpinner** [comment]
I'm glad that it's working for you now! :)
