### ISSUE TITLE
Make a suggestion, something really useful

### ISSUE THREAD

**Issue by epsilooos** [bulkpinner/bulkpinner#33]
Hello, excellent application!

I would like to make a suggestion, something really useful and what I think the bulkpinner should incorporate as soon as possible ....

The suggestion is that:
The field "Note for PIN" can be filled in automatically with the names of each of the images.

There is a "Use filename" function but you have to do it manually for each of the images and the idea is to automate the process.

This is very important, because when uploading many images with the same description, Pinterest bane the account, because it takes it as spam.

Thank you very much and I hope you can incorporate this improvement.

Greetings.

**Comment by bulkpinner** [comment]
Thank you for the suggestion!

I have taken note of it :).

Regards,
Luke
