### ISSUE TITLE
The Pinner was working fine and now it won't load load my boards. 

### ISSUE THREAD

**Issue by swankwc** [bulkpinner/bulkpinner#34]
The title pretty much says it all.

**Comment by Blinndox** [comment]
Having the same issue. Disconnected and reconnected. Pinner doesn't seem to be working anymore in any fashion.

**Comment by bulkpinner** [comment]
Thanks for the report.

Pinterest have let me know that people have been using Bulk Pinner to spam Pinterest, and therefore they've revoked the applications access.

I will have to reassess how people use Bulk Pinner now.
