### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by hanisgithub** [bulkpinner/bulkpinner#36]
hey, is it possible you add some new features? i'd like to be able to add the same caption to all my pictures at once so i dont have to do it multiple times.. otherwise its great!! thank you so much.

**Comment by bulkpinner** [comment]
Hi hanisgithub!

Bulk Pinner isn't currently working. I've noticed that someone else has taken my code and re-uploaded it under a different URL, trying to pass it off as their own as they've also changed the donate link to point to their account, so I would suggest getting in contact with them to make updates :).

Thanks!
