### ISSUE TITLE
problem accessing folder. unable to authorise

### ISSUE THREAD

**Issue by ghost** [bulkpinner/bulkpinner#4]
{"status": "failure", "message": "You are not permitted to access that resource.", "code": 7, "data": "The provided redirect_uri http://bulkpinner.app/ does not match any of the registered redirect URIs."}

**Comment by bulkpinner** [comment]
Hi ghost,

Thank you for the bug report! Unfortunately GitHub doesn't appear to be redirecting traffic through to https properly yet, after I updated the URL for Bulk Pinner.

In the mean time, could you please try going directly to [https://bulkpinner.com](https://bulkpinner.com).

Kind regards,
Luke

**Comment by EDwardM5** [comment]
Still not working 
![image](https://user-images.githubusercontent.com/40632301/41973012-4959c578-79d9-11e8-83b6-89bc8b1de16e.png)

not even the url it can be fixed?
