### ISSUE TITLE
What is the problem

### ISSUE THREAD

**Issue by ekocem89** [bulkpinner/bulkpinner#42]
what is the problem why do you turn off comments

**Comment by bulkpinner** [comment]
Hi ekocem89,

Can you please let me know which URL you are accessing Bulk Pinner on?

Thanks

**Comment by ekocem89** [comment]
internetsokagi.com

**Comment by ekocem89** [comment]
pinterest boards do not come. Pinterest has made the update and your token may have been canceled

**Comment by bulkpinner** [comment]
I'm not in control of the code that is on that URL. `bulkpinner.app` is the only URL that contains code that I control. Other domains are just people that have been taking the code that I've generously open sourced, and attempting to pass it off as their own

**Comment by ekocem89** [comment]
Bulk Pinner temporarily disabled
I received an email today indicating that Bulk Pinner's access to Pinterest has been revoked.

The reason I was given is because people have been using Bulk Pinner to spam Pinterest.

I will now have to reassess how to move forward with Bulk Pinner, as I don't want people who are doing the right thing to miss out on using the tool.

I don't know how long it will take before Bulk Pinner regains its access to Pinterest.
