### ISSUE TITLE
https://bulkpinner.app

### ISSUE THREAD

**Issue by ekocem89** [bulkpinner/bulkpinner#43]
http://bulkpinner.app get this alert for website

Bulk Pinner temporarily disabled
I received an email today indicating that Bulk Pinner's access to Pinterest has been revoked.

The reason I was given is because people have been using Bulk Pinner to spam Pinterest.

I will now have to reassess how to move forward with Bulk Pinner, as I don't want people who are doing the right thing to miss out on using the tool.

I don't know how long it will take before Bulk Pinner regains its access to Pinterest.

**Comment by bulkpinner** [comment]
I am aware of the note. There is nothing I can do, Pinterest don't care about the development community
