### ISSUE TITLE
Is API banned?

### ISSUE THREAD

**Issue by melihkavraz** [bulkpinner/bulkpinner#44]
Hi, 

I used to use bulkpinner but for 4-5 days I couldn't pin anything. Will you update your API?

**Comment by bulkpinner** [comment]
Hi melihkavraz,

May I ask, which URL were you accessing Bulk Pinner through?

**Comment by melihkavraz** [comment]
bulkpinner.com

Is that wrong?

**Comment by bulkpinner** [comment]
Unfortunately, yes. Someone has taken my code and uploaded it to their own domain, passing it off as their own - even updating the development donate link to point to their account! I have no control over any instance of Bulk Pinner that isn't on bulkpinner.app
