### ISSUE TITLE
Bulk pinner not loading board

### ISSUE THREAD

**Issue by AngilaRose** [bulkpinner/bulkpinner#45]
I've been using bulk pinner.com and it is absolutely amazing but I accidentally disconnected and when I tried to reconnect to my Pinterest account, it no longer loads my boards at all so I can't pin. Is there any way to fix this issue?

**Comment by bulkpinner** [comment]
Hi AngilaRose,

I'm glad you like Bulk Pinner. Unfortunately, the _real_ Bulk Pinner (bulkpinner.app) hasn't been working for some time. Bulkpinner.com is someone's re-upload of my work that I generously open sourced, but they're trying to pass it off as their own, even updating the donate link to point to their own account!

So with that in mind, you'll have to contact them to fix the issue :).

Luke
