### ISSUE TITLE
Bulk Pinner doesn't load any of my board 

### ISSUE THREAD

**Issue by fredconv** [bulkpinner/bulkpinner#48]
Hi 

Trying to use the bulk pinner, but even if i have my board set as public , and did the authorized process, the board dropdown is still loading forever and doesn't display any board at all .

And i get no visible error message feeback .

Seems to be related to 

 has been blocked by CORS policy: No 'Access-Control-Allow-Origin'

**Comment by bulkpinner** [comment]
Hi Frederic,

I don't control bulkpinner.com. Please report your issue to the person who does.

Kind regards
