### ISSUE TITLE
Bulkpinner "status": "failure", "message"

### ISSUE THREAD

**Issue by sdams** [bulkpinner/bulkpinner#6]
Hello

I have always been able to authorize Bulkpinner but since last week I can't get past this message:
{"status": "failure", "message": "You are not permitted to access that resource.", "code": 7, "data": "The provided redirect_uri http://bulkpinner.app/ does not match any of the registered redirect URIs."}

Not sure what to do. Is this a known issue?

Yours
Fons

**Comment by bulkpinner** [comment]
Hi Fons,

I'm currently having issues with GitHub not redirecting to HTTPS reliably.

Could you please visit https://bulkpinner.app instead, then it should work fine 😀

Thanks
Luke

**Comment by sdams** [comment]
Thanks Luke!
Yours
Stijn
