### ISSUE TITLE
Hello Luke Denton

### ISSUE THREAD

**Issue by elwinjose** [bulkpinner/bulkpinner#7]
My name is Elwin Jose, I'm testing the Pinterest tool.

I have a query, as I can put description and URL to all post.

I have observed that you explain how to do it, but I do not understand exactly.
Can you please tell me.

**Comment by bulkpinner** [comment]
Hi Elwin,

If I understand your query correctly, you'd like to know how to automatically populate all of the description and link fields in each of the pin previews?

To do that, you will need to fill in the description and link for the first pin preview, and then type `>` character 3 times. So, hold the `shift` key, then press `.` three times. You should ensure that no text field or textarea has focus when you type the characters (if you can see > > > appearing, then the shortcut won't work)

I hope that helps :)

Luke

**Comment by elwinjose** [comment]
![screenshot_6](https://user-images.githubusercontent.com/32841779/42331658-fcb5da9c-8043-11e8-80eb-61ea41200b4f.png)
You can send me a capture because I do and I do not work. Please

**Comment by bulkpinner** [comment]
The keyboard shortcut isn't going to work while the text input is active. It's the same as keyboard shortcuts everywhere else in a computer operating system.
As you can see ">>>" appearing in your description, this means the field is still active.
If you click on some whitespace outside of any text input, but still inside your browser, then try the shortcut, it should work

**Comment by elwinjose** [comment]
I really don't understand.
You can do it for the Team View on my Pc.

I'll give you a donation, please.

**Comment by bulkpinner** [comment]
I'm not going to do it via team viewer, because that way i won't be able to teach properly, and other people will miss out on seeing how it's done.
Another option which will be easier, once you finish typing your description, press the escape key on your keyboard, then try the shortcut

**Comment by elwinjose** [comment]
1-I write the text I want.
2-At the end of the text I put this (> > >)
Example: This is my input text > > >

Then I put my text and at the end of the text put the 3 characters > > >, what else should I do?

**Comment by bulkpinner** [comment]
Only put ">>>" in your description if you want that to appear on Pinterest, having it typed in your description is now how the shortcut works.

1. Type the text you want in the description
2. Press the Esc key on your keyboard (should be top left corner of your keyboard)
3. Press and hold the shift key
4. Tap the full stop key 3 times

You won't see anything being typed when you do this

**Comment by elwinjose** [comment]
No, I can't or won't.

We can communicate by some via
Messenger, Whatsapp, Skype?

**Comment by elwinjose** [comment]
Yes, but in case of raising 500 pins because the work would be difficult.

But I'm going to keep trying.

Have a tool that can edit the link of a pin and uploaded to Pinterest?

**Comment by bulkpinner** [comment]
Unfortunately not

**Comment by elwinjose** [comment]
Ok, now I'm starting with Google Adsense and SEO.

So monetize my pages, do you have sales tools?
