### ISSUE TITLE
Boards not loading

### ISSUE THREAD

**Issue by KittyOh** [bulkpinner/bulkpinner#8]
Hi
It seems to get stuck loading boards, and below under each pin it says there are no boards.
Can it only upload to public boards? I'm trying to bulk upload to secret boards.
Thanks!
![screen shot 2018-07-11 at 14 26 11](https://user-images.githubusercontent.com/41117726/42574559-861410d4-8516-11e8-9526-a595a2cb6944.png)
![screen shot 2018-07-11 at 14 26 04](https://user-images.githubusercontent.com/41117726/42574560-863cccf4-8516-11e8-9679-df9bcdd5496c.png)

**Comment by bulkpinner** [comment]
Hi KittyOh,

Bulk Pinner will only upload to public boards unfortunately. This is a limitation within Pinterest's API, as it doesn't return secret boards.
I have noticed that the API still returns archived pubic boards though, so you could create a public board, archive it, then upload your pins to it and use Pinterest's bulk move tool to move them to your secret board. That might keep them from appearing on anyone elses feed.

Thanks
Luke

**Comment by KittyOh** [comment]
Many thanks for your answer and suggested solution - we wanted to use it to upload confidential work, to share between our team, so I think using archive boards might be too risky. But good to know your tool exists if we need to bulk upload to public boards in future, thanks!
