### ISSUE TITLE
Cannot switch pinterest accounts

### ISSUE THREAD

**Issue by mittensthexcat4** [bulkpinner/bulkpinner#9]
Great app.
Recently has sever log in issues with Pinterest, and had to reset PW 3 times.
Bulkpinner now will not switch accounts. I manually cleared all session cookies and storage, and now I get this message.

status | "failure"
-- | --
message | "Authentication failed."
code | 2
data | null

Can this be fixed.
Ralph

**Comment by bulkpinner** [comment]
Hi Ralph,

Thanks for the feedback!

I'm curious, where exactly is the "Authentication failed" message being shown? Is it possible to get a screenshot of it, so I can see it in context?

Thanks
Luke
